name: 'Chromatic'
on: push
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Build addon
        run: yarn workspace msw-storybook-addon build
      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          workingDir: ./packages/docs
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
